import {
  EDITAR_NIVEL_ORGANIZACIONAL,
  EDITAR_NIVEL_ORGANIZACIONAL_EXITO,
  EDITAR_NIVEL_ORGANIZACIONAL_ERROR,
  EDITAR_UNIDAD_ORGANIZACIONAL,
  EDITAR_UNIDAD_ORGANIZACIONAL_EXITO,
  EDITAR_UNIDAD_ORGANIZACIONAL_ERROR,
  AGREGAR_NIVEL_ORGANIZACIONAL,
  AGREGAR_NIVEL_ORGANIZACIONAL_ERROR,
  AGREGAR_NIVEL_ORGANIZACIONAL_EXITO,
  AGREGAR_UNIDAD_ORGANIZACIONAL,
  AGREGAR_UNIDAD_ORGANIZACIONAL_ERROR,
  AGREGAR_UNIDAD_ORGANIZACIONAL_EXITO,
  ELIMINAR_NIVEL_ORGANIZACIONAL,
  ELIMINAR_NIVEL_ORGANIZACIONAL_ERROR,
  ELIMINAR_NIVEL_ORGANIZACIONAL_EXITO,
  ELIMINAR_UNIDAD_ORGANIZACIONAL,
  ELIMINAR_UNIDAD_ORGANIZACIONAL_ERROR,
  ELIMINAR_UNIDAD_ORGANIZACIONAL_EXITO,
} from "../types/edicionOrganigramaTypes";

export const editarEstacionAction = () => {
  return async (dispatch) => {
    dispatch()
  };
};
