export const COMENZAR_DESCARGA_ALARMAS_CONFIG = "COMENZAR_DESCARGA_ALARMAS_CONFIG";
export const DESCARGA_ALARMAS_CONFIG_ERROR = "DESCARGA_ALARMAS_CONFIG_ERROR";
export const DESCARGA_ALARMAS_CONFIG_COMPLETADO = "DESCARGA_ALARMAS_CONFIG_COMPLETADO";

export const PETICION_OBTENER_ALARMA_CONFIG_EDIT = "PETICION_OBTENER_ALARMA_CONFIG_EDIT";
export const OBTENER_ALARMA_CONFIG_EDIT_COMPLETADO = "OBTENER_ALARMA_CONFIG_EDIT_COMPLETADO";
export const OBTENER_ALARMA_CONFIG_EDIT_ERROR = "OBTENER_ALARMA_CONFIG_EDIT_ERROR";

export const PETICION_EDITAR_ALARMA_CONFIG = "PETICION_EDITAR_ALARMA_CONFIG";
export const EDITAR_ALARMA_CONFIG_COMPLETADO = "EDITAR_ALARMA_CONFIG_COMPLETADO";
export const EDITAR_ALARMA_CONFIG_ERROR = "EDITAR_ALARMA_CONFIG_ERROR";