export const COMENZAR_DESCARGA_ALARMAS = "COMENZAR_DESCARGA_ALARMAS";
export const DESCARGA_ALARMAS_ERROR = "DESCARGA_ALARMAS_ERROR";
export const DESCARGA_ALARMAS_COMPLETADO = "DESCARGA_ALARMAS_COMPLETADO";

export const PETICION_ELIMINAR_ALARMA = "PETICION_ELIMINAR_ALARMA";
export const ELIMINAR_ALARMA_COMPLETADO = "ELIMINAR_ALARMA_COMPLETADO";
export const ELIMINAR_ALARMA_ERROR = "PETICION_ELIMINAR_ALARMA";

export const PETICION_AGREGAR_ALARMA = "PETICION_AGREGAR_ALARMA";
export const AGREGAR_ALARMA_COMPLETADO = "AGREGAR_ALARMA_COMPLETADO";
export const AGREGAR_ALARMA_ERROR = "AGREGAR_ALARMA_ERROR";

export const PETICION_OBTENER_ALARMA_EDIT = "PETICION_OBTENER_ALARMA_EDIT";
export const OBTENER_ALARMA_EDIT_COMPLETADO = "OBTENER_ALARMA_EDIT_COMPLETADO";
export const OBTENER_ALARMA_EDIT_ERROR = "OBTENER_ALARMA_EDIT_ERROR";

export const CAMBIAR_MODO = "CAMBIAR_MODO";

export const PETICION_EDITAR_ALARMA = "PETICION_EDITAR_ALARMA";
export const EDITAR_ALARMA_COMPLETADO = "EDITAR_ALARMA_COMPLETADO";
export const EDITAR_ALARMA_ERROR = "EDITAR_ALARMA_ERROR";
