export const COMENZAR_DESCARGA_ALARMAS_CONFIG = "COMENZAR_DESCARGA_ALARMAS_CONFIG";
export const DESCARGA_ALARMAS_CONFIG_ERROR = "DESCARGA_ALARMAS_CONFIG_ERROR";
export const DESCARGA_ALARMAS_CONFIG_COMPLETADO = "DESCARGA_ALARMAS_CONFIG_COMPLETADO";

export const PETICION_OBTENER_ALARMA_CONFIG_EDIT = "PETICION_OBTENER_ALARMA_CONFIG_EDIT";
export const OBTENER_ALARMA_CONFIG_EDIT_COMPLETADO = "OBTENER_ALARMA_CONFIG_EDIT_COMPLETADO";
export const OBTENER_ALARMA_CONFIG_EDIT_ERROR = "OBTENER_ALARMA_CONFIG_EDIT_ERROR";