export const AGREGAR_BODEGA = "AGREGAR_BODEGA";
export const AGREGAR_BODEGA_EXITO = "AGREGAR_BODEGA_EXITO";
export const AGREGAR_BODEGA_ERROR = "AGREGAR_BODEGA_ERROR";

export const COMENZAR_DESCARGA_BODEGAS = "COMENZAR_DESCARGA_BODEGA";
export const DESCARGA_BODEGAS_EXITO = "DESCARGA_BODEGAS_EXITO";
export const DESCARGA_BODEGAS_ERROR = "DESCARGA_BODEGAS_ERROR";

export const OBTENER_BODEGA_ELIMINAR = "ELIMINAR_BODEGA";
export const ELIMINAR_BODEGA_EXITO = "ELIMINAR_BODEGA_EXITO";
export const ELIMINAR_BODEGA_ERROR = "ELIMINAR_BODEGA_ERROR";

export const OBTENER_BODEGA_EDITAR = "OBTENER_BODEGA_EDITAR";
export const EDITAR_BODEGA_EXITO = "EDITAR_BODEGA_EXITO";
export const EDITAR_BODEGA_ERROR = "EDITAR_BODEGA_ERROR";

export const OBTENER_BODEGA_BY_EDIT_REQUEST = "OBTENER_BODEGA_BY_EDIT_REQUEST";
export const OBTENER_BODEGA_BY_EDIT_SUCCESS = "OBTENER_BODEGA_BY_EDIT_SUCCESS";
export const OBTENER_BODEGA_BY_EDIT_FAIL = "OBTENER_BODEGA_BY_EDIT_FAIL";