export const AGREGAR_BODEGA = "AGREGAR_BODEGA";
export const AGREGAR_BODEGA_EXITO = "AGREGAR_BODEGA_EXITO";
export const AGREGAR_BODEGA_ERROR = "AGREGAR_BODEGA_ERROR";

export const COMENZAR_DESCARGA_BODEGAS = "COMENZAR_DESCARGA_BODEGA";
export const DESCARGA_BODEGAS_EXITO = "DESCARGA_BODEGAS_EXITO";
export const DESCARGA_BODEGAS_ERROR = "DESCARGA_BODEGAS_ERROR";


export const ELIMINAR_BODEGA = "ELIMINAR_BODEGA";
export const ELIMINAR_BODEGA_EXITO = "ELIMINAR_BODEGA_EXITO";
export const ELIMINAR_BODEGA_ERROR = "ELIMINAR_BODEGA_ERROR";