export const COMENZAR_DESCARGA_CONFIGURACIONES = "COMENZAR_DESCARGA_CONFIGURACIONES";
export const DESCARGA_CONFIGURACIONES_EXITO = "DESCARGA_CONFIGURACIONES_EXITO";
export const DESCARGA_CONFIGURACIONES_ERROR = "DESCARGA_CONFIGURACIONES_ERROR";

export const OBTENER_CONFIGURACION_EDITAR = "OBTENER_CONFIGURACION_EDITAR";
export const COMENZAR_EDICION_CONFIGURACION = "COMENZAR_EDICION_CONFIGURACION";
export const CONFIGURACION_EDITADO_EXITO = "CONFIGURACION_EDITADO_EXITO";
export const CONFIGURACION_EDITADO_ERROR = "CONFIGURACION_EDITADO_ERROR";