export const AGREGAR_MARCA = "AGREGAR_MARCA";
export const AGREGAR_MARCA_EXITO = "AGREGAR_MARCA_EXITO";
export const AGREGAR_MARCA_ERROR = "AGREGAR_MARCA_ERROR";

export const COMENZAR_DESCARGA_MARCA = "COMENZAR_DESCARGA_MARCA";
export const DESCARGA_MARCA_EXITO = "DESCARGA_MARCA_EXITO";
export const DESCARGA_MARCA_ERROR = "DESCARGA_MARCA_ERROR";

export const OBTENER_MARCA_ELIMINAR = "ELIMINAR_MARCA";
export const ELIMINAR_MARCA_EXITO = "ELIMINAR_MARCA_EXITO";
export const ELIMINAR_MARCA_ERROR = "ELIMINAR_MARCA_ERROR";