export const AGREGAR_ORGANIGRAMA = "AGREGAR_ORGANIGRAMA"
export const AGREGAR_ORGANIGRAMA_EXITO = "AGREGAR_ORGANIGRAMA_EXITO"
export const AGREGAR_ORGANIGRAMA_ERROR = "AGREGAR_ORGANIGRAMA_ERROR"

export const DESCARGAR_ORGANIGRAMA = "DESCARGAR_ORGANIGRAMA"
export const DESCARGAR_ORGANIGRAMA_EXITO = "DESCARGAR_ORGANIGRAMA_EXITO"
export const DESCARGAR_ORGANIGRAMA_ERROR = "DESCARGAR_ORGANIGRAMA_ERROR"

export const EDITAR_ORGANIGRAMA_OBTENER = "EDITAR_ORGANIGRAMA_OBTENER"
export const EDITAR_ORGANIGRAMA = "EDITAR_ORGANIGRAMA"
export const EDITAR_ORGANIGRAMA_EXITO = "EDITAR_ORGANIGRAMA_EXITO"
export const EDITAR_ORGANIGRAMA_ERROR = "EDITAR_ORGANIGRAMA_ERROR"

export const ELIMINAR_OBTENER_ORGANIGRAMA = "ELIMINAR_OBTENER_ORGANIGRAMA"
export const ELIMINAR_ORGANIGRAMA = "ELIMINAR_ORGANIGRAMA"
export const ELIMINAR_ORGANIGRAMA_EXITO = "ELIMINAR_ORGANIGRAMA_EXITO"
export const ELIMINAR_ORGANIGRAMA_ERROR = "ELIMINAR_ORGANIGRAMA_ERROR"
