export const AGREGAR_ESTACION = "AGREGAR_ESTACION";
export const AGREGAR_ESTACION_EXITO = "AGREGAR_ESTACION_EXITO";
export const AGREGAR_ESTACION_ERROR = "AGREGAR_ESTACION_ERROR";

export const COMENZAR_DESCARGA_ESTACIONES = "COMENZAR_DESCARGA_ESTACIONES";
export const DESCARGA_ESTACIONES_EXITO = "DESCARGA_ESTACIONES_EXITO";
export const DESCARGA_ESTACIONES_ERROR = "DESCARGA_ESTACIONES_ERROR";

export const OBTENER_ESTACION_ELIMINAR = "OBTENER_ESTACION_ELIMINAR";
export const ESTACION_ELIMINADO_EXITO = "ESTACION_ELIMINADO_EXITO";
export const ESTACION_ELIMINADO_ERROR = "ESTACION_ELIMINADO_ERROR";

export const OBTENER_ESTACION_EDITAR = "OBTENER_ESTACION_EDITAR";
export const COMENZAR_EDICION_ESTACION = "COMENZAR_EDICION_ESTACION";
export const ESTACION_EDITADO_EXITO = "ESTACION_EDITADO_EXITO";
export const ESTACION_EDITADO_ERROR = "ESTACION_EDITADO_ERROR";