export const AGREGAR_ESTACION = "AGREGAR_ESTACION";
export const AGREGAR_ESTACION_EXITO = "AGREGAR_ESTACION_EXITO";
export const AGREGAR_ESTACION_ERROR = "AGREGAR_ESTACION_ERROR";

export const COMENZAR_DESCARGA_ESTACIONES = "COMENZAR_DESCARGA_ESTACIONES";
export const DESCARGA_ESTACIONES_EXITO = "DESCARGA_ESTACIONES_EXITO";
export const DESCARGA_ESTACIONES_ERROR = "DESCARGA_ESTACIONES_ERROR";

export const OBTENER_ESTACION_ELIMINAR = "OBTENER_ESTACION_ELIMINAR";
export const ESTACION_ELIMINADO_EXITO = "ESTACION_ELIMINADO_EXITO";
export const ESTACION_ELIMINADO_ERROR = "ESTACION_ELIMINADO_ERROR";

export const OBTENER_ESTACION_EDITAR = "OBTENER_ESTACION_EDITAR";
export const COMENZAR_EDICION_ESTACION = "COMENZAR_EDICION_ESTACION";
export const ESTACION_EDITADO_EXITO = "ESTACION_EDITADO_EXITO";
export const ESTACION_EDITADO_ERROR = "ESTACION_EDITADO_ERROR";

//Usuarios

export const AGREGAR_USUARIO = "AGREGAR_USUARIO";
export const AGREGAR_USUARIO_EXITO = "AGREGAR_USUARIO_EXITO";
export const AGREGAR_USUARIO_ERROR = "AGREGAR_USUARIO_ERROR";

export const COMENZAR_DESCARGA_USUARIOS = "COMENZAR_DESCARGA_USUARIOS";
export const DESCARGA_USUARIOS_EXITO = "DESCARGA_USUARIOS_EXITO";
export const DESCARGA_USUARIOS_ERROR = "DESCARGA_USUARIOS_ERROR";

export const OBTENER_USUARIO_ELIMINAR = "OBTENER_USUARIO_ELIMINAR";
export const USUARIO_ELIMINADO_EXITO = "USUARIO_ELIMINADO_EXITO";
export const USUARIO_ELIMINADO_ERROR = "USUARIO_ELIMINADO_ERROR";

export const OBTENER_USUARIO_EDITAR = "OBTENER_USUARIO_EDITAR";
export const COMENZAR_EDICION_USUARIO = "COMENZAR_EDICION_USUARIO";
export const USUARIO_EDITADO_EXITO = "USUARIO_EDITADO_EXITO";
export const USUARIO_EDITADO_ERROR = "USUARIO_EDITADO_ERROR";