export const COMENZAR_DESCARGA_MONITOREO = "COMENZAR_DESCARGA_MONITOREO";
export const DESCARGA_MONITOREO_EXITO = "DESCARGA_MONITOREO_EXITO";
export const DESCARGA_MONITOREO_ERROR = "DESCARGA_MONITOREO_ERROR";

export const OBTENER_MONITOREO_EDITAR = "OBTENER_MONITOREO_EDITAR";
export const COMENZAR_EDICION_MONITOREO = "COMENZAR_EDICION_MONITOREO";
export const MONITOREO_EDITADO_EXITO = "MONITOREO_EDITADO_EXITO";
export const MONITOREO_EDITADO_ERROR = "MONITOREO_EDITADO_ERROR";