export const COMENZAR_DESCARGA_NOTIFICACIONES = "COMENZAR_DESCARGA_NOTIFICACIONES";
export const DESCARGA_NOTIFICACIONES_EXITO = "DESCARGA_NOTIFICACIONES_EXITO";
export const DESCARGA_NOTIFICACIONES_ERROR = "DESCARGA_NOTIFICACIONES_ERROR";