export const COMENZAR_DESCARGA_NOTIFICACIONES =
  "COMENZAR_DESCARGA_NOTIFICACIONES";
export const DESCARGA_NOTIFICACIONES_EXITO = "DESCARGA_NOTIFICACIONES_EXITO";
export const DESCARGA_NOTIFICACIONES_ERROR = "DESCARGA_NOTIFICACIONES_ERROR";

export const PETICION_ELIMINAR_NOTIFICACION = "PETICION_ELIMINAR_NOTIFICACION";
export const ELIMINAR_NOTIFICACION_COMPLETADO =
  "ELIMINAR_NOTIFICACION_COMPLETADO";
export const ELIMINAR_NOTIFICACION_ERROR = "ELIMINAR_NOTIFICACION_ERROR";

export const CAMBIAR_MODO = "CAMBIAR_MODO";

export const PETICION_AGREGAR_NOTIFICACION = "PETICION_AGREGAR_NOTIFICACION";
export const AGREGAR_NOTIFICACION_COMPLETADO =
  "AGREGAR_NOTIFICACION_COMPLETADO";
export const AGREGAR_NOTIFICACION_ERROR = "AGREGAR_NOTIFICACION_ERROR";

export const PETICION_OBTENER_NOTIFICACION_EDIT =
  "PETICION_OBTENER_NOTIFICACION_EDIT";
export const OBTENER_NOTIFICACION_EDIT_COMPLETADO =
  "OBTENER_NOTIFICACION_EDIT_COMPLETADO";
export const OBTENER_NOTIFICACION_EDIT_ERROR =
  "OBTENER_NOTIFICACION_EDIT_ERROR";

export const PETICION_EDITAR_NOTIFICACION = "PETICION_EDITAR_NOTIFICACION";
export const EDITAR_NOTIFICACION_COMPLETADO = "EDITAR_NOTIFICACION_COMPLETADO";
export const EDITAR_NOTIFICACION_ERROR = "EDITAR_NOTIFICACION_ERROR";
