export const AGREGAR_ORGANIGRAMA = "AGREGAR_ORGANIGRAMA"
export const AGREGAR_ORGANIGRAMA_ERROR = "AGREGAR_ORGANIGRAMA_ERROR"

export const DESCARGAR_ORGANIGRAMA = "DESCARGAR_ORGANIGRAMA"
export const DESCARGAR_ORGANIGRAMA_EXITO = "DESCARGAR_ORGANIGRAMA_EXITO"
export const DESCARGAR_ORGANIGRAMA_ERROR = "DESCARGAR_ORGANIGRAMA_ERROR"

export const EDITAR_ORGANIGRAMA_OBTENER = "EDITAR_ORGANIGRAMA_OBTENER"

export const ELIMINAR_OBTENER_ORGANIGRAMA = "ELIMINAR_OBTENER_ORGANIGRAMA"
export const ELIMINAR_ORGANIGRAMA = "ELIMINAR_ORGANIGRAMA"
export const ELIMINAR_ORGANIGRAMA_EXITO = "ELIMINAR_ORGANIGRAMA_EXITO"
export const ELIMINAR_ORGANIGRAMA_ERROR = "ELIMINAR_ORGANIGRAMA_ERROR"

//Finalizar
export const FINALIZAR_ORGANIGRAMA = "FINALIZAR_ORGANIGRAMA"
export const FINALIZAR_ORGANIGRAMA_ERROR = "FINALIZAR_ORGANIGRAMA_ERROR"

//Agregar Niveles
export const AGREGAR_NIVEL_ORGANIZACIONAL = "AGREGAR_NIVEL_ORGANIZACIONAL"
export const AGREGAR_NIVEL_ORGANIZACIONAL_EXITO = "AGREGAR_NIVEL_ORGANIZACIONAL_EXITO"
export const AGREGAR_NIVEL_ORGANIZACIONAL_ERROR = "AGREGAR_NIVEL_ORGANIZACIONAL_ERROR"

//Obtener Niveles
export const OBTENER_NIVELES_ORGANIGRAMA_OBTENER = "OBTENER_NIVELES_ORGANIGRAMA_OBTENER"
export const OBTENER_NIVELES_ORGANIGRAMA_ERROR = "OBTENER_NIVELES_ORGANIGRAMA_ERROR"

//Obtener Unidades
export const OBTENER_UNIDADES_ORGANIGRAMA_OBTENER = "OBTENER_UNIDADES_ORGANIGRAMA_OBTENER"
export const OBTENER_UNIDADES_ORGANIGRAMA_ERROR = "OBTENER_UNIDADES_ORGANIGRAMA_ERROR"