export const AGREGAR_UNIDADMEDIDA = "AGREGAR_UNIDADMEDIDA";
export const AGREGAR_UNIDADMEDIDA_EXITO = "AGREGAR_UNIDADMEDIDA_EXITO";
export const AGREGAR_UNIDADMEDIDA_ERROR = "AGREGAR_UNIDADMEDIDA_ERROR";

export const COMENZAR_DESCARGA_UNIDADMEDIDA = "COMENZAR_DESCARGA_UNIDADMEDIDA";
export const DESCARGA_UNIDADMEDIDA_EXITO = "DESCARGA_UNIDADMEDIDA_EXITO";
export const DESCARGA_UNIDADMEDIDA_ERROR = "DESCARGA_UNIDADMEDIDA_ERROR";

export const OBTENER_UNIDADMEDIDA_ELIMINAR = "ELIMINAR_UNIDADMEDIDA";
export const ELIMINAR_UNIDADMEDIDA_EXITO = "ELIMINAR_UNIDADMEDIDA_EXITO";
export const ELIMINAR_UNIDADMEDIDA_ERROR = "ELIMINAR_UNIDADMEDIDA_ERROR";